In [1]:
print ("hello")

hello


In [3]:
import numpy as np

In [4]:
a = np.array([1, 2, 3])
print(a)
a[1] = 21
print(a)

[1 2 3]
[ 1 21  3]


In [5]:
print(a.shape)
print(a.dtype)
print(a.size)

(3,)
int32
3


In [6]:
b = a * np.array([2, 0, 2])
print(b)

[2 0 6]


In [7]:
my_list = [1, 2, 3]
print(type(my_list))
print(type(b))
b += 2
print(b)

<class 'list'>
<class 'numpy.ndarray'>
[4 2 8]


In [8]:
print(np.dot(a, b))

70


In [9]:
c = np.random.randn(1000)
d = np.random.randn(1000)
print(np.dot(c, d))

25.247172245816166


In [10]:
print(c)

[-1.89264791e+00 -4.90836901e-01 -8.73273353e-02  6.20165242e-01
  1.15872573e-01  2.07244668e-01  1.88621156e-01  1.76260004e+00
  3.64721284e-01 -1.30992628e+00 -1.14219093e+00 -5.65593296e-01
 -4.84226321e-02  1.57163656e+00  1.12567838e+00 -1.09083690e-01
  6.90721894e-02 -5.03707760e-01  1.09714936e+00  2.09453635e-01
  5.38668946e-01  3.88729753e-01  3.49318797e-01 -8.60864782e-01
  1.14775471e+00 -4.62787177e-01 -3.02287797e-02 -1.18775338e+00
  5.76345054e-01  1.73187890e+00  2.99261566e-01 -1.16946478e+00
  3.04334335e-01 -1.68327015e+00  1.06017264e+00 -1.81515643e+00
  8.09400695e-01  6.13607826e-01 -1.05402717e+00  1.41226212e-02
  6.08674271e-01  2.75149704e-01  9.06734181e-01 -6.34560552e-02
 -6.52477397e-01 -1.07060931e-01  1.88999792e+00  3.82616155e-02
 -9.87595192e-01 -2.36093521e-01 -1.31817688e+00  2.99589210e-01
  3.96643781e-01 -7.95192902e-01 -9.28748919e-01 -1.42616958e+00
 -7.82497060e-01  4.88532535e-01 -1.18383290e+00 -1.21235338e-01
 -1.33306222e-01 -7.58018

In [22]:
dt = np.array([2,3,4,5])
print(dt)
#print(np.linalg.det(dt))

[2 3 4 5]


In [19]:
print(np.diag(dt))

[2 4]


In [20]:
sr = np.array([[1,2,4,5], [2,3,4,10]])
print(sr[1, 1:])

[ 3  4 10]


In [23]:
np.matmul(sr, dt)

array([49, 79])